# Generated by Django 3.1.14 on 2022-01-26 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroups',
            fields=[
                ('status', models.CharField(choices=[('E', 'ENABLED'), ('R', 'REMOVED')], max_length=1)),
                ('alias', models.CharField(max_length=30)),
                ('ad_group_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('structure_value', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('E', 'ENABLED'), ('R', 'REMOVED')], max_length=1)),
                ('campaign_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField()),
                ('cost', models.FloatField()),
                ('conversion_value', models.FloatField()),
                ('conversions', models.IntegerField()),
                ('search_term', models.TextField()),
                ('date', models.DateField()),
                ('roas', models.FloatField()),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidApp.adgroups')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidApp.campaigns')),
            ],
        ),
        migrations.AddField(
            model_name='adgroups',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidApp.campaigns'),
        ),
    ]
